name: '3.4'

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
 - task: NuGetToolInstaller@1
   inputs:
    versionSpec: '4.5'

 - task: NuGetCommand@2
   inputs:
     command: 'restore'
     restoreSolution: '**/*.sln'
     feedsToUse: 'select'

 - task: MSBuild@1
   inputs:
      solution: '**/TinySvgHelper.csproj'
      configuration: 'Release'
      msbuildArguments: '/t:pack /p:PackageVersion=$(Build.BuildNumber).$(Build.BuildId))'
      
 - task: CopyFiles@2
   inputs:
    Contents: '**/*nupkg'
    TargetFolder: '$(build.artifactstagingdirectory)'
   
 - task: PublishBuildArtifacts@1
   inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'packages'
        publishLocation: 'Container'